# ================= Auth Service =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: simple-microservices-auth-service
        ports:
        - containerPort: 8006
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/auth
        - name: JWT_SECRET
          value: mysecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8006
  type: ClusterIP

---
