apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-service
  template:
    metadata:
      labels:
        app: comments-service
    spec:
      containers:
      - name: comments-service
        image: simple-microservices-comments-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  type: NodePort
  selector:
    app: comments-service
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002

