apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: simple-microservices-event-bus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
  - port: 8005
    targetPort: 8005
    nodePort: 30005

