apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation-service
  template:
    metadata:
      labels:
        app: moderation-service
    spec:
      containers:
      - name: moderation-service
        image: simple-microservices-moderation-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  type: NodePort
  selector:
    app: moderation-service
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004

